"""Authoritative import-mapping contract consumed by the frontend wizard.

Per-field keys:
- ``op_types``: operation types where the field is offered as a mapping slot.
  Omitted = the field applies to every operation type.
- ``required_for``: operation types where mapping the field is mandatory.
- ``is_required``: mandatory for every operation type.
"""

from __future__ import annotations

IMPORT_METADATA = {
    "fields": [
        {
            "key": "operation_type",
            "label": "Action / Type",
            "is_required": True,
            "type": "enum",
            "enum_values": [
                "trade",
                "dividend",
                "interest",
                "expense",
                "revenue",
                "fx_rate_change",
                "transfer_in",
                "transfer_out",
                "stock_split",
                "fee",
                "tax",
            ],
        },
        {
            "key": "executed_at",
            "label": "Timestamp",
            "is_required": True,
            "type": "datetime",
        },
        {
            "key": "name",
            "label": "Asset Name / Label",
            "is_required": False,
            "type": "string",
        },
        {
            "key": "total_amount",
            "label": "Total Amount",
            "is_required": True,
            "type": "numeric",
        },
        {
            "key": "currency",
            "label": "Total Currency",
            "is_required": True,
            "type": "string",
        },
        {
            "key": "ticker",
            "label": "Ticker Symbol",
            "is_required": False,
            "type": "string",
            "op_types": ["trade", "dividend", "stock_split"],
            "required_for": ["trade", "stock_split"],
        },
        {
            "key": "isin",
            "label": "ISIN Number",
            "is_required": False,
            "type": "string",
            "op_types": ["trade", "dividend", "stock_split"],
        },
        {
            "key": "quantity",
            "label": "Quantity / Number of Shares",
            "is_required": False,
            "type": "numeric",
            "op_types": ["trade", "dividend", "stock_split"],
            "required_for": ["trade", "stock_split"],
        },
        {
            "key": "unit_price",
            "label": "Price Per Share",
            "is_required": False,
            "type": "numeric",
            "op_types": ["trade", "dividend"],
            "required_for": ["trade"],
        },
        {
            "key": "dividend_per_share",
            "label": "Dividend Per Share",
            "is_required": False,
            "type": "numeric",
            "op_types": ["dividend"],
        },
        {
            "key": "price_currency",
            "label": "Price Currency",
            "is_required": False,
            "type": "string",
            "op_types": ["trade", "dividend"],
        },
        {
            "key": "transaction_id",
            "label": "Transaction ID",
            "is_required": False,
            "type": "string",
        },
        {
            "key": "exchange_rate",
            "label": "Exchange Rate",
            "is_required": False,
            "type": "numeric",
            "required_for": ["fx_rate_change"],
        },
        {
            "key": "source_currency",
            "label": "Source Currency",
            "is_required": False,
            "type": "string",
            "op_types": ["fx_rate_change"],
            "required_for": ["fx_rate_change"],
        },
        {
            "key": "target_currency",
            "label": "Target Currency",
            "is_required": False,
            "type": "string",
            "op_types": ["fx_rate_change"],
            "required_for": ["fx_rate_change"],
        },
        # -- Trade-specific fields --
        {
            "key": "trade_side",
            "label": "Trade Side (Buy/Sell)",
            "is_required": False,
            "type": "enum",
            "enum_values": ["buy", "sell"],
            "op_types": ["trade"],
            "required_for": ["trade"],
        },
        {
            "key": "order_type",
            "label": "Order Type",
            "is_required": False,
            "type": "enum",
            "enum_values": ["market", "limit", "stop", "stop_limit"],
            "op_types": ["trade"],
        },
        {
            "key": "order_status",
            "label": "Order Status",
            "is_required": False,
            "type": "enum",
            "enum_values": ["pending", "partially_filled", "filled", "cancelled", "expired"],
            "op_types": ["trade"],
        },
        {
            "key": "limit_price",
            "label": "Limit Price",
            "is_required": False,
            "type": "numeric",
            "op_types": ["trade"],
        },
        {
            "key": "stop_price",
            "label": "Stop Price",
            "is_required": False,
            "type": "numeric",
            "op_types": ["trade"],
        },
        {
            "key": "execution_price",
            "label": "Execution Price",
            "is_required": False,
            "type": "numeric",
            "op_types": ["trade"],
        },
        {
            "key": "order_placed_at",
            "label": "Order Placed Date",
            "is_required": False,
            "type": "datetime",
            "op_types": ["trade"],
        },
        {
            "key": "filled_at",
            "label": "Order Filled Date",
            "is_required": False,
            "type": "datetime",
            "op_types": ["trade"],
        },
        # -- Fee / Tax fields --
        {
            "key": "fee_amount",
            "label": "Fee Amount",
            "is_required": False,
            "type": "numeric",
            "op_types": ["trade", "transfer_out", "fee"],
            "required_for": ["fee"],
        },
        {
            "key": "fee_currency",
            "label": "Fee Currency",
            "is_required": False,
            "type": "string",
            "op_types": ["trade", "transfer_out", "fee"],
        },
        {
            "key": "fee_category",
            "label": "Fee Category",
            "is_required": False,
            "type": "string",
            "op_types": ["trade", "transfer_out", "fee"],
        },
        {
            "key": "fee_type",
            "label": "Fee Type",
            "is_required": False,
            "type": "enum",
            "enum_values": ["conversion", "withholding_tax", "commission", "transaction", "other"],
            "op_types": ["trade", "transfer_out", "fee"],
        },
        {
            "key": "tax_amount",
            "label": "Tax Amount",
            "is_required": False,
            "type": "numeric",
            "op_types": ["trade", "dividend", "expense", "revenue", "tax"],
            "required_for": ["tax"],
        },
        {
            "key": "tax_currency",
            "label": "Tax Currency",
            "is_required": False,
            "type": "string",
            "op_types": ["trade", "dividend", "expense", "revenue", "tax"],
        },
        {
            "key": "tax_category",
            "label": "Tax Category",
            "is_required": False,
            "type": "string",
            "op_types": ["trade", "dividend", "expense", "revenue", "tax"],
        },
        # -- Everyday finance fields --
        {
            "key": "merchant_name",
            "label": "Merchant Name",
            "is_required": False,
            "type": "string",
            "op_types": ["expense", "revenue"],
        },
        {
            "key": "merchant_category",
            "label": "Merchant Category",
            "is_required": False,
            "type": "string",
            "op_types": ["expense", "revenue"],
        },
        {
            "key": "expense_category",
            "label": "Expense Category",
            "is_required": False,
            "type": "enum",
            "enum_values": [
                "groceries",
                "dining",
                "transport",
                "utilities",
                "entertainment",
                "healthcare",
                "education",
                "shopping",
                "travel",
                "subscription",
                "rent",
                "insurance",
                "other",
            ],
            "op_types": ["expense"],
        },
        {
            "key": "revenue_category",
            "label": "Revenue Category",
            "is_required": False,
            "type": "enum",
            "enum_values": [
                "salary",
                "freelance",
                "rental_income",
                "refund",
                "gift",
                "other",
            ],
            "op_types": ["revenue"],
        },
        {
            "key": "payment_method",
            "label": "Payment Method",
            "is_required": False,
            "type": "enum",
            "enum_values": [
                "card",
                "bank_transfer",
                "cash",
                "mobile_payment",
                "crypto",
                "other",
            ],
            "op_types": ["expense", "revenue"],
        },
        # -- Transfer fields --
        {
            "key": "source_reference",
            "label": "Source Reference",
            "is_required": False,
            "type": "string",
            "op_types": ["transfer_in", "fx_rate_change"],
        },
        {
            "key": "destination_reference",
            "label": "Destination Reference",
            "is_required": False,
            "type": "string",
            "op_types": ["transfer_out", "fx_rate_change"],
        },
        {
            "key": "interest_type",
            "label": "Interest Type",
            "is_required": False,
            "type": "enum",
            "enum_values": [
                "cash_interest",
                "cashback",
                "lending_interest",
                "bond_interest",
                "savings_interest",
                "margin_interest",
                "staking_rewards",
                "peer_to_peer_interest",
                "other",
            ],
            "op_types": ["interest"],
            "required_for": ["interest"],
        },
        # -- Stock split sub-type --
        {
            "key": "split_sub_type",
            "label": "Split Sub-type",
            "is_required": False,
            "type": "enum",
            "enum_values": ["close", "open", "combined"],
            "op_types": ["stock_split"],
        },
        {
            "key": "split_ratio",
            "label": "Split Ratio",
            "is_required": False,
            "type": "numeric",
            "op_types": ["stock_split"],
        },
        {
            "key": "pre_split_quantity",
            "label": "Pre-split Quantity",
            "is_required": False,
            "type": "numeric",
            "op_types": ["stock_split"],
        },
    ],
}
