from __future__ import annotations

IMPORT_METADATA = {
    "fields": [
        {
            "key": "operation_type",
            "label": "Action / Type",
            "is_required": True,
            "type": "enum",
            "enum_values": [
                "trade",
                "dividend",
                "interest",
                "expense",
                "revenue",
                "fx_rate_change",
                "transfer_in",
                "transfer_out",
                "stock_split",
                "fee",
                "tax",
            ],
        },
        {
            "key": "executed_at",
            "label": "Timestamp",
            "is_required": True,
            "type": "datetime",
        },
        {
            "key": "name",
            "label": "Asset Name / Label",
            "is_required": False,
            "type": "string",
        },
        {
            "key": "total_amount",
            "label": "Total Amount",
            "is_required": True,
            "type": "numeric",
        },
        {
            "key": "currency",
            "label": "Total Currency",
            "is_required": True,
            "type": "string",
        },
        {
            "key": "ticker",
            "label": "Ticker Symbol",
            "is_required": False,
            "type": "string",
        },
        {
            "key": "isin",
            "label": "ISIN Number",
            "is_required": False,
            "type": "string",
        },
        {
            "key": "quantity",
            "label": "Quantity",
            "is_required": False,
            "type": "numeric",
        },
        {
            "key": "unit_price",
            "label": "Price Per Share",
            "is_required": False,
            "type": "numeric",
        },
        {
            "key": "price_currency",
            "label": "Price Currency",
            "is_required": False,
            "type": "string",
        },
        {
            "key": "transaction_id",
            "label": "Transaction ID",
            "is_required": False,
            "type": "string",
        },
        {
            "key": "exchange_rate",
            "label": "Exchange Rate",
            "is_required": False,
            "type": "numeric",
        },
        # -- Trade-specific fields --
        {
            "key": "trade_side",
            "label": "Trade Side (Buy/Sell)",
            "is_required": False,
            "type": "enum",
            "enum_values": ["buy", "sell"],
        },
        {
            "key": "order_type",
            "label": "Order Type",
            "is_required": False,
            "type": "enum",
            "enum_values": ["market", "limit", "stop", "stop_limit"],
        },
        {
            "key": "order_status",
            "label": "Order Status",
            "is_required": False,
            "type": "enum",
            "enum_values": ["pending", "partially_filled", "filled", "cancelled", "expired"],
        },
        {
            "key": "limit_price",
            "label": "Limit Price",
            "is_required": False,
            "type": "numeric",
        },
        {
            "key": "stop_price",
            "label": "Stop Price",
            "is_required": False,
            "type": "numeric",
        },
        {
            "key": "execution_price",
            "label": "Execution Price",
            "is_required": False,
            "type": "numeric",
        },
        {
            "key": "order_placed_at",
            "label": "Order Placed Date",
            "is_required": False,
            "type": "datetime",
        },
        {
            "key": "filled_at",
            "label": "Order Filled Date",
            "is_required": False,
            "type": "datetime",
        },
        # -- Fee / Tax fields --
        {
            "key": "fee_amount",
            "label": "Fee Amount",
            "is_required": False,
            "type": "numeric",
        },
        {
            "key": "fee_currency",
            "label": "Fee Currency",
            "is_required": False,
            "type": "string",
        },
        {
            "key": "fee_type",
            "label": "Fee Type",
            "is_required": False,
            "type": "enum",
            "enum_values": ["conversion", "withholding_tax", "commission", "transaction", "other"],
        },
        {
            "key": "tax_amount",
            "label": "Tax Amount",
            "is_required": False,
            "type": "numeric",
        },
        {
            "key": "tax_currency",
            "label": "Tax Currency",
            "is_required": False,
            "type": "string",
        },
        # -- Everyday finance fields --
        {
            "key": "merchant_name",
            "label": "Merchant Name",
            "is_required": False,
            "type": "string",
        },
        {
            "key": "merchant_category",
            "label": "Merchant Category",
            "is_required": False,
            "type": "string",
        },
        {
            "key": "expense_category",
            "label": "Expense Category",
            "is_required": False,
            "type": "enum",
            "enum_values": [
                "groceries",
                "dining",
                "transport",
                "utilities",
                "entertainment",
                "healthcare",
                "education",
                "shopping",
                "travel",
                "subscription",
                "rent",
                "insurance",
                "other",
            ],
        },
        {
            "key": "revenue_category",
            "label": "Revenue Category",
            "is_required": False,
            "type": "enum",
            "enum_values": [
                "salary",
                "freelance",
                "rental_income",
                "refund",
                "gift",
                "other",
            ],
        },
        {
            "key": "payment_method",
            "label": "Payment Method",
            "is_required": False,
            "type": "enum",
            "enum_values": [
                "card",
                "bank_transfer",
                "cash",
                "mobile_payment",
                "crypto",
                "other",
            ],
        },
        # -- Transfer fields --
        {
            "key": "source_reference",
            "label": "Source Reference",
            "is_required": False,
            "type": "string",
        },
        {
            "key": "destination_reference",
            "label": "Destination Reference",
            "is_required": False,
            "type": "string",
        },
        {
            "key": "interest_type",
            "label": "Interest Type",
            "is_required": False,
            "type": "enum",
            "enum_values": [
                "cash_interest",
                "cashback",
                "lending_interest",
                "bond_interest",
                "savings_interest",
                "margin_interest",
                "staking_rewards",
                "peer_to_peer_interest",
                "other",
            ],
        },
    ],
}
