"""add interest_type to operation

Revision ID: 008195105719
Revises: 81c9cc58d0c9
Create Date: 2026-06-06 09:16:55.994323

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "008195105719"
down_revision: str | Sequence[str] | None = "81c9cc58d0c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operation",
        sa.Column(
            "interest_type",
            sa.Enum(
                "CASH_INTEREST",
                "CASHBACK",
                "LENDING_INTEREST",
                "BOND_INTEREST",
                "SAVINGS_INTEREST",
                "MARGIN_INTEREST",
                "STAKING_REWARDS",
                "PEER_TO_PEER_INTEREST",
                "OTHER",
                name="interesttype",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "interest_type")
    # ### end Alembic commands ###
