"""add is_incomplete to import_file_schema

Revision ID: 0debc6e014a8
Revises: ef655d33e4a6
Create Date: 2026-05-28 08:53:58.940959

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0debc6e014a8"
down_revision: str | Sequence[str] | None = "ef655d33e4a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("import_file_schema", sa.Column("is_incomplete", sa.Boolean(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("import_file_schema", "is_incomplete")
    # ### end Alembic commands ###
