"""add_emoji_and_sort_order_to_portfolio

Revision ID: 29f18c669cc1
Revises: 932393106f05
Create Date: 2026-07-04 22:27:07.814742

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29f18c669cc1"
down_revision: str | Sequence[str] | None = "932393106f05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("portfolio", sa.Column("emoji", sa.String(length=20), nullable=True))
    op.add_column("portfolio", sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("portfolio", "sort_order")
    op.drop_column("portfolio", "emoji")
    # ### end Alembic commands ###
