"""add price_currency to operation

Revision ID: 771ff53806cf
Revises: 0debc6e014a8
Create Date: 2026-06-02 09:00:33.242677

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "771ff53806cf"
down_revision: str | Sequence[str] | None = "0debc6e014a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("price_currency", sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "price_currency")
    # ### end Alembic commands ###
