"""add_trade_and_everyday_finance

Revision ID: 776a056369b8
Revises: 008195105719
Create Date: 2026-06-06 10:25:11.468344

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "776a056369b8"
down_revision: str | Sequence[str] | None = "008195105719"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operation",
        sa.Column("trade_side", sa.Enum("BUY", "SELL", name="tradeside"), nullable=True),
    )
    op.add_column(
        "operation",
        sa.Column("order_type", sa.Enum("MARKET", "LIMIT", "STOP", "STOP_LIMIT", name="ordertype"), nullable=True),
    )
    op.add_column(
        "operation",
        sa.Column(
            "order_status",
            sa.Enum("PENDING", "PARTIALLY_FILLED", "FILLED", "CANCELLED", "EXPIRED", name="orderstatus"),
            nullable=True,
        ),
    )
    op.add_column(
        "operation",
        sa.Column("stop_price", sa.Numeric(precision=20, scale=8), nullable=True),
    )
    op.add_column(
        "operation",
        sa.Column("execution_price", sa.Numeric(precision=20, scale=8), nullable=True),
    )
    op.add_column(
        "operation",
        sa.Column("order_placed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "operation",
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "operation",
        sa.Column(
            "expense_category",
            sa.Enum(
                "GROCERIES",
                "DINING",
                "TRANSPORT",
                "UTILITIES",
                "ENTERTAINMENT",
                "HEALTHCARE",
                "EDUCATION",
                "SHOPPING",
                "TRAVEL",
                "SUBSCRIPTION",
                "RENT",
                "INSURANCE",
                "OTHER",
                name="expensecategory",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "operation",
        sa.Column(
            "revenue_category",
            sa.Enum(
                "SALARY",
                "FREELANCE",
                "RENTAL_INCOME",
                "REFUND",
                "GIFT",
                "OTHER",
                name="revenuecategory",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "operation",
        sa.Column(
            "payment_method",
            sa.Enum(
                "CARD",
                "BANK_TRANSFER",
                "CASH",
                "MOBILE_PAYMENT",
                "CRYPTO",
                "OTHER",
                name="paymentmethod",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###

    # Data migration
    op.execute(
        "UPDATE operation SET operation_type = 'trade', trade_side = 'buy', "
        "order_type = 'market', order_status = 'filled' WHERE operation_type = 'buy'",
    )
    op.execute(
        "UPDATE operation SET operation_type = 'trade', trade_side = 'sell', "
        "order_type = 'market', order_status = 'filled' WHERE operation_type = 'sell'",
    )
    op.execute(
        "UPDATE operation SET operation_type = 'trade', trade_side = 'buy', "
        "order_type = 'limit', order_status = 'filled' WHERE operation_type = 'limit_buy'",
    )
    op.execute(
        "UPDATE operation SET operation_type = 'trade', trade_side = 'sell', "
        "order_type = 'limit', order_status = 'filled' WHERE operation_type = 'limit_sell'",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Data migration rollback
    op.execute(
        "UPDATE operation SET operation_type = 'buy' WHERE operation_type = 'trade' "
        "AND trade_side = 'buy' AND order_type = 'market'",
    )
    op.execute(
        "UPDATE operation SET operation_type = 'sell' WHERE operation_type = 'trade' "
        "AND trade_side = 'sell' AND order_type = 'market'",
    )
    op.execute(
        "UPDATE operation SET operation_type = 'limit_buy' WHERE operation_type = 'trade' "
        "AND trade_side = 'buy' AND order_type = 'limit'",
    )
    op.execute(
        "UPDATE operation SET operation_type = 'limit_sell' WHERE operation_type = 'trade' "
        "AND trade_side = 'sell' AND order_type = 'limit'",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "payment_method")
    op.drop_column("operation", "revenue_category")
    op.drop_column("operation", "expense_category")
    op.drop_column("operation", "filled_at")
    op.drop_column("operation", "order_placed_at")
    op.drop_column("operation", "execution_price")
    op.drop_column("operation", "stop_price")
    op.drop_column("operation", "order_status")
    op.drop_column("operation", "order_type")
    op.drop_column("operation", "trade_side")
    # ### end Alembic commands ###
