"""make_position_name_nullable

Revision ID: 81c9cc58d0c9
Revises: 771ff53806cf
Create Date: 2026-06-02 18:19:32.880805

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81c9cc58d0c9"
down_revision: str | Sequence[str] | None = "771ff53806cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("position") as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(length=300), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("position") as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(length=300), nullable=False)
    # ### end Alembic commands ###
