"""remove_ui_component_marketplace

Revision ID: 8de8926c9c6b
Revises: e4181cc04a9d
Create Date: 2026-06-25 09:20:10.251966

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8de8926c9c6b"
down_revision: str | Sequence[str] | None = "e4181cc04a9d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ui_component_variant_component_key"), table_name="ui_component_variant")
    op.drop_index(op.f("ix_ui_component_variant_is_active"), table_name="ui_component_variant")
    op.drop_index(op.f("ix_ui_component_variant_user_id"), table_name="ui_component_variant")
    op.drop_table("ui_component_variant")
    op.drop_index(op.f("ix_ui_component_override_component_key"), table_name="ui_component_override")
    op.drop_index(op.f("ix_ui_component_override_is_active"), table_name="ui_component_override")
    op.drop_index(op.f("ix_ui_component_override_user_id"), table_name="ui_component_override")
    op.drop_index(op.f("ix_ui_component_override_variant_id"), table_name="ui_component_override")
    op.drop_table("ui_component_override")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ui_component_override",
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("deleted_at", sa.DATETIME(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))"),
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("component_key", sa.VARCHAR(length=100), nullable=False),
        sa.Column("variant_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.ForeignKeyConstraint(["variant_id"], ["ui_component_variant.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ui_component_override_variant_id"),
        "ui_component_override",
        ["variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ui_component_override_user_id"),
        "ui_component_override",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ui_component_override_is_active"),
        "ui_component_override",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ui_component_override_component_key"),
        "ui_component_override",
        ["component_key"],
        unique=False,
    )
    op.create_table(
        "ui_component_variant",
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("deleted_at", sa.DATETIME(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))"),
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("component_key", sa.VARCHAR(length=100), nullable=False),
        sa.Column("name", sa.VARCHAR(length=150), nullable=False),
        sa.Column("description", sa.VARCHAR(length=500), nullable=False),
        sa.Column("asset_url", sa.VARCHAR(length=500), nullable=False),
        sa.Column("is_public", sa.BOOLEAN(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ui_component_variant_user_id"),
        "ui_component_variant",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ui_component_variant_is_active"),
        "ui_component_variant",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ui_component_variant_component_key"),
        "ui_component_variant",
        ["component_key"],
        unique=False,
    )
    # ### end Alembic commands ###
