"""add_pre_split_quantity_to_operation

Revision ID: 932393106f05
Revises: d885e6e8adc1
Create Date: 2026-07-02 20:43:52.974746

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "932393106f05"
down_revision: str | Sequence[str] | None = "d885e6e8adc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("pre_split_quantity", sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "pre_split_quantity")
    # ### end Alembic commands ###
