"""initial_migration

Revision ID: d885e6e8adc1
Revises:
Create Date: 2026-07-01 12:55:23.378175

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d885e6e8adc1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institution",
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_institution_is_active"), "institution", ["is_active"], unique=False)
    op.create_table(
        "user",
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("theme", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_is_active"), "user", ["is_active"], unique=False)
    op.create_index(op.f("ix_user_public_id"), "user", ["public_id"], unique=True)
    op.create_table(
        "financial_account",
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
        sa.Column("account_number", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["institution_id"], ["institution.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_financial_account_institution_id"), "financial_account", ["institution_id"], unique=False)
    op.create_index(op.f("ix_financial_account_is_active"), "financial_account", ["is_active"], unique=False)
    op.create_table(
        "import_file_schema",
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("delimiter", sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
        sa.Column("decimal_separator", sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
        sa.Column("mappings", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_incomplete", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_import_file_schema_is_active"), "import_file_schema", ["is_active"], unique=False)
    op.create_index(op.f("ix_import_file_schema_user_id"), "import_file_schema", ["user_id"], unique=False)
    op.create_table(
        "portfolio",
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_portfolio_is_active"), "portfolio", ["is_active"], unique=False)
    op.create_index(op.f("ix_portfolio_user_id"), "portfolio", ["user_id"], unique=False)
    op.create_table(
        "position",
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "asset_type",
            sa.Enum("CASH", "CRYPTO", "ETF", "STOCK", "BOND", "COMMODITY", "FUND", "OTHER", name="assettype"),
            nullable=False,
        ),
        sa.Column("ticker", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
        sa.Column("isin", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolio.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_position_asset_type"), "position", ["asset_type"], unique=False)
    op.create_index(op.f("ix_position_is_active"), "position", ["is_active"], unique=False)
    op.create_index(op.f("ix_position_isin"), "position", ["isin"], unique=False)
    op.create_index(op.f("ix_position_portfolio_id"), "position", ["portfolio_id"], unique=False)
    op.create_index(op.f("ix_position_ticker"), "position", ["ticker"], unique=False)
    op.create_table(
        "operation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation_type", sa.String(length=30), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("price_currency", sa.String(length=3), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("transaction_id", sa.String(length=100), nullable=True),
        sa.Column("exchange_rate", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("source_currency", sa.String(length=3), nullable=True),
        sa.Column("target_currency", sa.String(length=3), nullable=True),
        sa.Column("trade_side", sa.Enum("BUY", "SELL", name="tradeside"), nullable=True),
        sa.Column("order_type", sa.Enum("MARKET", "LIMIT", "STOP", "STOP_LIMIT", name="ordertype"), nullable=True),
        sa.Column(
            "order_status",
            sa.Enum("PENDING", "PARTIALLY_FILLED", "FILLED", "CANCELLED", "EXPIRED", name="orderstatus"),
            nullable=True,
        ),
        sa.Column("limit_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("execution_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("order_placed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "expense_category",
            sa.Enum(
                "GROCERIES",
                "DINING",
                "TRANSPORT",
                "UTILITIES",
                "ENTERTAINMENT",
                "HEALTHCARE",
                "EDUCATION",
                "SHOPPING",
                "TRAVEL",
                "SUBSCRIPTION",
                "RENT",
                "INSURANCE",
                "OTHER",
                name="expensecategory",
            ),
            nullable=True,
        ),
        sa.Column(
            "revenue_category",
            sa.Enum("SALARY", "FREELANCE", "RENTAL_INCOME", "REFUND", "GIFT", "OTHER", name="revenuecategory"),
            nullable=True,
        ),
        sa.Column(
            "payment_method",
            sa.Enum("CARD", "BANK_TRANSFER", "CASH", "MOBILE_PAYMENT", "CRYPTO", "OTHER", name="paymentmethod"),
            nullable=True,
        ),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("financial_account_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("dividend_per_share", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("fee_category", sa.String(length=100), nullable=True),
        sa.Column("tax_category", sa.String(length=100), nullable=True),
        sa.Column(
            "interest_type",
            sa.Enum(
                "CASH_INTEREST",
                "CASHBACK",
                "LENDING_INTEREST",
                "BOND_INTEREST",
                "SAVINGS_INTEREST",
                "MARGIN_INTEREST",
                "STAKING_REWARDS",
                "PEER_TO_PEER_INTEREST",
                "OTHER",
                name="interesttype",
            ),
            nullable=True,
        ),
        sa.Column("source_reference", sa.String(length=300), nullable=True),
        sa.Column("destination_reference", sa.String(length=300), nullable=True),
        sa.Column("split_ratio", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("merchant_name", sa.String(length=200), nullable=True),
        sa.Column("merchant_category", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["financial_account_id"], ["financial_account.id"]),
        sa.ForeignKeyConstraint(["position_id"], ["position.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_operation_executed_at", "operation", ["executed_at"], unique=False)
    op.create_index("ix_operation_financial_account_id", "operation", ["financial_account_id"], unique=False)
    op.create_index("ix_operation_position_id", "operation", ["position_id"], unique=False)
    op.create_index(op.f("ix_operation_transaction_id"), "operation", ["transaction_id"], unique=False)
    op.create_index("ix_operation_type", "operation", ["operation_type"], unique=False)
    op.create_table(
        "fee",
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column(
            "fee_type",
            sa.Enum("CONVERSION", "WITHHOLDING_TAX", "COMMISSION", "TRANSACTION", "OTHER", name="feetype"),
            nullable=False,
        ),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
        sa.Column("operation_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["operation_id"], ["operation.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fee_fee_type"), "fee", ["fee_type"], unique=False)
    op.create_index(op.f("ix_fee_is_active"), "fee", ["is_active"], unique=False)
    op.create_index(op.f("ix_fee_operation_id"), "fee", ["operation_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fee_operation_id"), table_name="fee")
    op.drop_index(op.f("ix_fee_is_active"), table_name="fee")
    op.drop_index(op.f("ix_fee_fee_type"), table_name="fee")
    op.drop_table("fee")
    op.drop_index("ix_operation_type", table_name="operation")
    op.drop_index(op.f("ix_operation_transaction_id"), table_name="operation")
    op.drop_index("ix_operation_position_id", table_name="operation")
    op.drop_index("ix_operation_financial_account_id", table_name="operation")
    op.drop_index("ix_operation_executed_at", table_name="operation")
    op.drop_table("operation")
    op.drop_index(op.f("ix_position_ticker"), table_name="position")
    op.drop_index(op.f("ix_position_portfolio_id"), table_name="position")
    op.drop_index(op.f("ix_position_isin"), table_name="position")
    op.drop_index(op.f("ix_position_is_active"), table_name="position")
    op.drop_index(op.f("ix_position_asset_type"), table_name="position")
    op.drop_table("position")
    op.drop_index(op.f("ix_portfolio_user_id"), table_name="portfolio")
    op.drop_index(op.f("ix_portfolio_is_active"), table_name="portfolio")
    op.drop_table("portfolio")
    op.drop_index(op.f("ix_import_file_schema_user_id"), table_name="import_file_schema")
    op.drop_index(op.f("ix_import_file_schema_is_active"), table_name="import_file_schema")
    op.drop_table("import_file_schema")
    op.drop_index(op.f("ix_financial_account_is_active"), table_name="financial_account")
    op.drop_index(op.f("ix_financial_account_institution_id"), table_name="financial_account")
    op.drop_table("financial_account")
    op.drop_index(op.f("ix_user_public_id"), table_name="user")
    op.drop_index(op.f("ix_user_is_active"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_institution_is_active"), table_name="institution")
    op.drop_table("institution")
    # ### end Alembic commands ###
