"""add_import_metadata_columns_and_tables

Revision ID: ef655d33e4a6
Revises:
Create Date: 2026-05-26 08:56:22.469948

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef655d33e4a6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("transaction_id", sa.String(length=100), nullable=True))
    op.add_column("operation", sa.Column("merchant_name", sa.String(length=200), nullable=True))
    op.add_column("operation", sa.Column("merchant_category", sa.String(length=100), nullable=True))
    op.create_index(op.f("ix_operation_transaction_id"), "operation", ["transaction_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operation_transaction_id"), table_name="operation")
    op.drop_column("operation", "merchant_category")
    op.drop_column("operation", "merchant_name")
    op.drop_column("operation", "transaction_id")
    # ### end Alembic commands ###
