import type { ColMapping, ColumnConfig } from './types';
import { getMappedColIdxForField, getColumnConfigForField } from './validation';
import { evaluateFormulaTokens, parseNumericCell } from './formula';

export function parsePreviewRows(params: {
  allRawRows: string[][];
  importDecimalSep: string;
  operationTypeColumnIdx: number | null;
  operationTypeMappings: Record<string, string>;
  columnConfigMap: Record<string, Partial<ColumnConfig> & { global?: ColMapping }>;
  uiColumns: Array<{ id: string; colIdx: number; name?: string }>;
  importFields: any[];
}) {
  if (!params.allRawRows?.length || params.operationTypeColumnIdx === null) return [];

  const previewRows = params.allRawRows.slice(0, 5);
  return previewRows.map(cells => {
    const getVal = (idx: number) => (idx >= 0 && idx < cells.length ? cells[idx] : '');

    const rowByHeader: Record<string, string> = {};
    params.uiColumns.forEach(col => {
      if (col?.name !== undefined) rowByHeader[col.name] = getVal(col.colIdx);
    });

    const rawAction = getVal(params.operationTypeColumnIdx!).trim();
    const opType = params.operationTypeMappings[rawAction] || 'unknown';

    const getMappedVal = (dbKey: string) => {
      const idx = getMappedColIdxForField(dbKey, rawAction, opType, params.columnConfigMap, params.uiColumns);
      return getVal(idx);
    };

    const applyTrans = (dbKey: string, rawVal: string) => {
      const conf = getColumnConfigForField(params.columnConfigMap, dbKey, rawAction, opType);
      let num: number | null;
      if (conf?.formula?.length) {
        num = evaluateFormulaTokens(conf.formula, rowByHeader, params.importDecimalSep);
      } else {
        num = parseNumericCell(rawVal, params.importDecimalSep);
      }
      if (num === null) return rawVal;
      if (conf?.divisor) num /= conf.divisor;
      if (conf?.multiplier) num *= conf.multiplier;
      return num.toString();
    };

    // Formula-mapped fields have a value even when no direct column is mapped.
    const getNumericVal = (dbKey: string): string => {
      const conf = getColumnConfigForField(params.columnConfigMap, dbKey, rawAction, opType);
      const rawVal = getMappedVal(dbKey);
      if (!conf?.formula?.length && !rawVal) return '';
      return applyTrans(dbKey, rawVal);
    };

    const ticker = getMappedVal('ticker');
    const isin = getMappedVal('isin');
    const rawName = getMappedVal('name');
    const nameWasSet = !!(rawName && rawName.trim());
    const name = nameWasSet ? rawName.trim() : (ticker || isin || 'Asset');

    const rawQty = getMappedVal('quantity');
    const rawPrice = getMappedVal('unit_price');
    const rawPriceCurrency = getMappedVal('price_currency');
    const rawTotal = getMappedVal('total_amount');
    const rawCurrency = getMappedVal('currency');

    const parsedPrice = getNumericVal('unit_price') || rawPrice;
    const parsedTotal = getNumericVal('total_amount') || rawTotal;

    const displayCurrency = rawCurrency || 'EUR';
    const displayPriceCurrency = rawPriceCurrency || displayCurrency;

    const feesList: string[] = [];
    const parsedFee = getNumericVal('fee_amount');
    if (parsedFee && parseFloat(parsedFee) > 0) {
      const rawFeeType = getMappedVal('fee_type');
      let resolvedFeeType = 'conversion';
      if (rawFeeType) {
        const idx = getMappedColIdxForField('fee_type', rawAction, opType, params.columnConfigMap, params.uiColumns);
        if (idx !== -1) {
          const conf = getColumnConfigForField(params.columnConfigMap, 'fee_type', rawAction, opType);
          resolvedFeeType = conf?.enumMappings?.[rawFeeType] || 'conversion';
        }
      }
      feesList.push(`${parsedFee} ${getMappedVal('fee_currency') || displayCurrency} (${resolvedFeeType})`);
    }

    const parsedTax = getNumericVal('tax_amount');
    if (parsedTax && parseFloat(parsedTax) > 0) {
      feesList.push(`${parsedTax} ${getMappedVal('tax_currency') || displayCurrency} (tax)`);
    }

    const txIdIdx = getMappedColIdxForField('transaction_id', rawAction, opType, params.columnConfigMap, params.uiColumns);
    const rawTxId = txIdIdx !== -1 ? getVal(txIdIdx) : '';
    let transactionId = rawTxId?.trim() || '';
    let isTxIdAutoGenerated = false;

    const txConf = getColumnConfigForField(params.columnConfigMap, 'transaction_id', rawAction, opType);
    const enrichTxOpt = txConf?.enrichTransactionIds || 'when_empty';

    // Matches the backend: no transaction_id column is required for auto-generation.
    const shouldGenerate =
      (enrichTxOpt === 'always') ||
      (enrichTxOpt === 'when_empty' && !transactionId);

    if (shouldGenerate) {
      // Create a deterministic mock hash based on cells content
      const serialized = cells.join(',');
      let hash1 = 5381;
      let hash2 = 52711;
      for (let i = 0; i < serialized.length; i++) {
        const char = serialized.charCodeAt(i);
        hash1 = (hash1 * 33) ^ char;
        hash2 = (hash2 * 37) ^ char;
      }
      const h1 = Math.abs(hash1).toString(16).padStart(8, '0');
      const h2 = Math.abs(hash2).toString(16).padStart(8, '0');
      const mockHash = (h1 + h2).slice(0, 16);
      transactionId = `auto-${mockHash}`;
      isTxIdAutoGenerated = true;
    }

    return {
      time: getMappedVal('executed_at'),
      action: rawAction,
      opType,
      ticker,
      name,
      rawName: rawName?.trim() || '',
      nameWasSet,
      isin,
      quantity: getNumericVal('quantity') || rawQty,
      price: parsedPrice,
      priceCurrency: displayPriceCurrency,
      total: parsedTotal,
      currency: displayCurrency,
      fees: feesList.join(', ') || 'None',
      merchant: getMappedVal('merchant_name')
        ? `${getMappedVal('merchant_name')} (${getMappedVal('merchant_category')})`
        : '—',
      transactionId,
      rawTransactionId: rawTxId?.trim() || '',
      isTxIdAutoGenerated
    };
  });
}
