import type { ColMapping } from './types';
import { getMappedColIdxForField, getColumnConfigForField } from './validation';

export function parsePreviewRows(params: {
  fileText: string;
  importDelimiter: string;
  importDecimalSep: string;
  operationTypeColumnIdx: number | null;
  operationTypeMappings: Record<string, string>;
  columnConfigMap: Record<string, { global: ColMapping; typeSpecific: Record<string, ColMapping> }>;
  uiColumns: Array<{ id: string; colIdx: number }>;
  importFields: any[];
}) {
  if (!params.fileText || !params.importDelimiter || params.operationTypeColumnIdx === null) return [];

  const lines = params.fileText.split('\n').map(l => l.trim()).filter(l => l.length > 0);
  if (lines.length <= 1) return [];


  const previewLines = lines.slice(1, 6);
  return previewLines.map(line => {
    const cells = line.split(params.importDelimiter).map(c => c.trim().replace(/^["']|["']$/g, ''));
    const getVal = (idx: number) => (idx >= 0 && idx < cells.length ? cells[idx] : '');

    const rawAction = getVal(params.operationTypeColumnIdx!).trim();
    const opType = params.operationTypeMappings[rawAction] || 'unknown';

    const getMappedVal = (dbKey: string) => {
      const idx = getMappedColIdxForField(dbKey, rawAction, opType, params.columnConfigMap, params.uiColumns);
      return getVal(idx);
    };

    const applyTrans = (dbKey: string, rawVal: string) => {
      let num = parseFloat(rawVal.replace(params.importDecimalSep === '.' ? ',' : '.', '').replace(params.importDecimalSep, '.'));
      if (isNaN(num)) return rawVal;

      const idx = getMappedColIdxForField(dbKey, rawAction, opType, params.columnConfigMap, params.uiColumns);
      if (idx !== -1) {
        const conf = getColumnConfigForField(params.columnConfigMap, dbKey, rawAction, opType);
        if (conf?.divisor) num /= conf.divisor;
        if (conf?.multiplier) num *= conf.multiplier;
      }
      return num.toString();
    };

    const ticker = getMappedVal('ticker');
    const isin = getMappedVal('isin');
    const rawName = getMappedVal('name');
    const nameWasSet = !!(rawName && rawName.trim());
    const name = nameWasSet ? rawName.trim() : (ticker || isin || 'Asset');

    const rawQty = getMappedVal('quantity');
    const rawPrice = getMappedVal('unit_price');
    const rawPriceCurrency = getMappedVal('price_currency');
    const rawTotal = getMappedVal('total_amount');
    const rawCurrency = getMappedVal('currency');

    let parsedPrice = rawPrice;
    if (rawPrice) parsedPrice = applyTrans('unit_price', rawPrice);
    let parsedTotal = rawTotal;
    if (rawTotal) parsedTotal = applyTrans('total_amount', rawTotal);

    const displayCurrency = rawCurrency || 'EUR';
    const displayPriceCurrency = rawPriceCurrency || displayCurrency;

    const feesList: string[] = [];
    const feeAmtVal = getMappedVal('fee_amount');
    if (feeAmtVal && parseFloat(feeAmtVal) > 0) {
      const parsedFee = applyTrans('fee_amount', feeAmtVal);
      const rawFeeType = getMappedVal('fee_type');
      let resolvedFeeType = 'conversion';
      if (rawFeeType) {
        const idx = getMappedColIdxForField('fee_type', rawAction, opType, params.columnConfigMap, params.uiColumns);
        if (idx !== -1) {
          const conf = getColumnConfigForField(params.columnConfigMap, 'fee_type', rawAction, opType);
          resolvedFeeType = conf?.enumMappings?.[rawFeeType] || 'conversion';
        }
      }
      feesList.push(`${parsedFee} ${getMappedVal('fee_currency') || displayCurrency} (${resolvedFeeType})`);
    }

    const taxAmtVal = getMappedVal('tax_amount');
    if (taxAmtVal && parseFloat(taxAmtVal) > 0) {
      const parsedTax = applyTrans('tax_amount', taxAmtVal);
      feesList.push(`${parsedTax} ${getMappedVal('tax_currency') || displayCurrency} (tax)`);
    }

    const txIdIdx = getMappedColIdxForField('transaction_id', rawAction, opType, params.columnConfigMap, params.uiColumns);
    const rawTxId = txIdIdx !== -1 ? getVal(txIdIdx) : '';
    let transactionId = rawTxId?.trim() || '';
    let isTxIdAutoGenerated = false;

    const txConf = getColumnConfigForField(params.columnConfigMap, 'transaction_id', rawAction, opType);
    const enrichTxOpt = txConf?.enrichTransactionIds || 'when_empty';

    const shouldGenerate =
      txIdIdx !== -1 && (
        (enrichTxOpt === 'always') ||
        (enrichTxOpt === 'when_empty' && !transactionId)
      );

    if (shouldGenerate) {
      // Create a deterministic mock hash based on cells content
      const serialized = cells.join(',');
      let hash1 = 5381;
      let hash2 = 52711;
      for (let i = 0; i < serialized.length; i++) {
        const char = serialized.charCodeAt(i);
        hash1 = (hash1 * 33) ^ char;
        hash2 = (hash2 * 37) ^ char;
      }
      const h1 = Math.abs(hash1).toString(16).padStart(8, '0');
      const h2 = Math.abs(hash2).toString(16).padStart(8, '0');
      const mockHash = (h1 + h2).slice(0, 16);
      transactionId = `auto-${mockHash}`;
      isTxIdAutoGenerated = true;
    }

    return {
      time: getMappedVal('executed_at'),
      action: rawAction,
      opType,
      ticker,
      name,
      rawName: rawName?.trim() || '',
      nameWasSet,
      isin,
      quantity: rawQty ? applyTrans('quantity', rawQty) : '',
      price: parsedPrice,
      priceCurrency: displayPriceCurrency,
      total: parsedTotal,
      currency: displayCurrency,
      fees: feesList.join(', ') || 'None',
      merchant: getMappedVal('merchant_name')
        ? `${getMappedVal('merchant_name')} (${getMappedVal('merchant_category')})`
        : '—',
      transactionId,
      rawTransactionId: rawTxId?.trim() || '',
      isTxIdAutoGenerated
    };
  });
}
