"""Deterministic idempotency keys for raw transaction ingestion.

Pure, stateless helpers used by the import pipeline to derive a stable,
collision-resistant deduplication key for every ingested row.

Strategy:
- If the source row carries a native unique identifier, it is used verbatim
  (deduplication is then exact and cheap).
- Otherwise a deterministic ``auto-<sha256>`` key is derived from the row's
  meaningful fields, salted with the ingestion *scope* (the target financial
  account) so identical raw rows never collide across unrelated accounts.

Defensive validation rejects corrupted rows (e.g. a row that only carries a
single field) before hashing, guaranteeing keys are derived from enough signal
to stay stable and collision-free.
"""

from __future__ import annotations

import hashlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Mapping

# A row must carry at least this many non-empty fields to yield a stable hash.
MIN_MEANINGFUL_FIELDS = 2

# ASCII control separators keep delimiter characters inside values from
# forging a different-but-colliding canonical form.
_FIELD_SEP = "\x1f"  # unit separator between "key=value" pairs
_SCOPE_SEP = "\x1e"  # record separator between scope salt and the row body

AUTO_PREFIX = "auto-"


class RowValidationError(ValueError):
    """Raised when a row is too sparse/corrupted to derive a stable id."""


def _normalize(value: object) -> str:
    """Collapse surrounding and internal whitespace to a single-space form."""
    return " ".join(str(value).strip().split())


def count_meaningful_fields(row: Mapping[str, object]) -> int:
    """Return the number of fields that carry a non-empty value."""
    return sum(1 for value in row.values() if value is not None and _normalize(value))


def canonicalize_row(row: Mapping[str, object]) -> str:
    """Serialize a row into a stable, order-independent canonical string.

    Keys are sorted, values normalized, and empty fields dropped so cosmetic
    differences (column order, padding, blank optional columns) never change
    the resulting hash.
    """
    parts = [
        f"{_normalize(key)}={_normalize(row[key])}"
        for key in sorted(row)
        if row[key] is not None and _normalize(row[key])
    ]
    return _FIELD_SEP.join(parts)


def compute_dedup_key(
    row: Mapping[str, object],
    *,
    scope: str,
    native_id: str | None = None,
    min_fields: int = MIN_MEANINGFUL_FIELDS,
) -> tuple[str, bool]:
    """Derive a deterministic deduplication key for an ingested row.

    Args:
        row: The raw source row (e.g. a CSV ``DictReader`` record).
        scope: Ingestion scope salt — typically the target financial account.
        native_id: The row's native unique id, if the source provides one.
        min_fields: Minimum non-empty fields required to hash a row safely.

    Returns:
        A ``(dedup_key, is_native)`` tuple. ``is_native`` is ``True`` when the
        key is the source-provided identifier and ``False`` when it was
        auto-generated by hashing.

    Raises:
        RowValidationError: If no native id is present and the row does not
            carry enough meaningful fields to derive a stable hash.
    """
    native = native_id.strip() if native_id and native_id.strip() else None
    if native:
        return native, True

    meaningful = count_meaningful_fields(row)
    if meaningful < min_fields:
        msg = (
            f"Row has {meaningful} meaningful field(s); at least {min_fields} "
            "are required to derive a stable deduplication key."
        )
        raise RowValidationError(msg)

    payload = f"{_normalize(scope)}{_SCOPE_SEP}{canonicalize_row(row)}"
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    return f"{AUTO_PREFIX}{digest}", False


def is_auto_generated(dedup_key: str | None) -> bool:
    """Return ``True`` if *dedup_key* was produced by hashing (not native)."""
    return bool(dedup_key and dedup_key.startswith(AUTO_PREFIX))
